# config.py

import os

# AI configuration
MODEL = "gpt-5.5"
FAST_MODEL = "gpt-4o"
STREAM = True
N = 1
PRESENCE_PENALTY = 0

# File paths
STATE_DIR = ".cligpt"
SYSTEM_MESSAGE_FILE = "system_message.txt"
CONTEXT_FILE = "context.txt"
SOURCES_DIR = "sources"
PERMANENT_MEMORY_FILE = "permanent_memory.json"  # permanent memories stored here

# Upload limits
MAX_UPLOAD_FILES = 500
MAX_DIRECTORY_FILES = 5000
MAX_DIRECT_VISION_UPLOADS = 25
MAX_UPLOAD_RETRIES = 3
DEFAULT_INDEX_CONCURRENCY = 8
INDEX_ETA_INTERVAL_SECONDS = 300
INDEX_ETA_INTERVAL_FILES = 100
MAX_DIRECT_PDF_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_COMPRESSED_PDF_UPLOAD_BYTES = 5 * 1024 * 1024
DEFAULT_OUTPUT_STYLE = os.getenv("CLIGPT_STYLE", "auto")
DEFAULT_HEARTBEAT_SECONDS = 30
DEFAULT_IDLE_TIMEOUT_SECONDS = 600
DEFAULT_REQUEST_TIMEOUT_SECONDS = 3600

# Token limits
MAX_OUTPUT_TOKENS = 100_000
MAX_CONTEXT_TOKENS = MAX_OUTPUT_TOKENS

# Delimiter for context blocks
DELIMITER = "\n" + "-" * 15 + "\n"
